# You can scan UUID of entity with nether star
admin:
    checkUUID: "celeskyshop.admin.uuid"

# Sign buy system
signs:
    settings:
        world: "world"
        signTitle: "[AchatShop]"
    # You need to create on LuckPerm plugins 5 groups
    # Your groups if shop:<group>
    # Example : shop:ramasseur
    ranks:
        level1: "Ramasseur"
        level2: "Revendeur"
        level3: "Grossiste"
        level4: "Courtier"
        level5: "Magnat"

# NPC settings
sellers:
    Blocks: 
        UUID: "f03e7f77-a9ad-20e8-8a23-7b7a5b28f23e"
        shopName: "§a§lVendeur de blocs"
        shopPermission: "celeskyshop.Blocks"
        shopLevel1: "celeskyshop.Blocks.level1"
        shopLevel2: "celeskyshop.Blocks.level2"
        shopLevel3: "celeskyshop.Blocks.level3"
        shopLevel4: "celeskyshop.Blocks.level4"
        shopLevel5: "celeskyshop.Blocks.level5"
    Blacksmith: 
        UUID: "773791ac-3a20-253b-8530-0ba389d4b25c"
        shopName: "§a§lForgeron"
        shopPermission: "celeskyshop.Blacksmith"
        shopLevel1: "celeskyshop.Blacksmith.level1"
        shopLevel2: "celeskyshop.Blacksmith.level2"
        shopLevel3: "celeskyshop.Blacksmith.level3"
        shopLevel4: "celeskyshop.Blacksmith.level4"
        shopLevel5: "celeskyshop.Blacksmith.level5"
    Carpenter: 
        UUID: "719fe9e2-a6c3-2971-bd35-817152f8da74"
        shopName: "§a§lMenuisier"
        shopPermission: "celeskyshop.Carpenter"
        shopLevel1: "celeskyshop.Carpenter.level1"
        shopLevel2: "celeskyshop.Carpenter.level2"
        shopLevel3: "celeskyshop.Carpenter.level3"
        shopLevel4: "celeskyshop.Carpenter.level4"
        shopLevel5: "celeskyshop.Carpenter.level5"
    Farmer: 
        UUID: "998bcbb3-e595-251f-b87d-04995a535dfc"
        shopName: "§a§lAgriculteur"
        shopPermission: "celeskyshop.Farmer"
        shopLevel1: "celeskyshop.Farmer.level1"
        shopLevel2: "celeskyshop.Farmer.level2"
        shopLevel3: "celeskyshop.Farmer.level3"
        shopLevel4: "celeskyshop.Farmer.level4"
        shopLevel5: "celeskyshop.Farmer.level5"
    Butcher: 
        UUID: "8e8e281f-881d-244b-a28f-c84687c3a0e6"
        shopName: "§a§lBoucher"
        shopPermission: "celeskyshop.Butcher"
        shopLevel1: "celeskyshop.Butcher.level1"
        shopLevel2: "celeskyshop.Butcher.level2"
        shopLevel3: "celeskyshop.Butcher.level3"
        shopLevel4: "celeskyshop.Butcher.level4"
        shopLevel5: "celeskyshop.Butcher.level5"
    Miner:
        UUID: "23ae30b4-87b0-266a-8395-6d40ff3110e8"
        shopName: "§a§lMineur"
        shopPermission: "celeskyshop.Miner"
        shopLevel1: "celeskyshop.Miner.level1"
        shopLevel2: "celeskyshop.Miner.level2"
        shopLevel3: "celeskyshop.Miner.level3"
        shopLevel4: "celeskyshop.Miner.level4"
        shopLevel5: "celeskyshop.Miner.level5"
    Magician:
        UUID: "707fdca0-55a4-2653-938b-e02ac2c8a053"
        shopName: "§a§lMagicien"
        shopPermission: "celeskyshop.Magician"
        shopLevel1: "celeskyshop.Magician.level1"
        shopLevel2: "celeskyshop.Magician.level2"
        shopLevel3: "celeskyshop.Magician.level3"
        shopLevel4: "celeskyshop.Magician.level4"
        shopLevel5: "celeskyshop.Magician.level5"
    Engineer:
        UUID: "c4af228a-6cd2-2644-97ce-ebcba75145d2"
        shopName: "§a§lIngénieur"
        shopPermission: "celeskyshop.Engineer"
        shopLevel1: "celeskyshop.Engineer.level1"
        shopLevel2: "celeskyshop.Engineer.level2"
        shopLevel3: "celeskyshop.Engineer.level3"
        shopLevel4: "celeskyshop.Engineer.level4"
        shopLevel5: "celeskyshop.Engineer.level5"
    Adventurer:
        UUID: "ed7d1e16-a764-2b8d-8311-e604a5e9fd18"
        shopName: "§a§lAventurier"
        shopPermission: "celeskyshop.Adventurer"
        shopLevel1: "celeskyshop.Adventurer.level1"
        shopLevel2: "celeskyshop.Adventurer.level2"
        shopLevel3: "celeskyshop.Adventurer.level3"
        shopLevel4: "celeskyshop.Adventurer.level4"
        shopLevel5: "celeskyshop.Adventurer.level5"
    Hero:
        UUID: "66844676-207e-2647-ad55-63b13b44c252"
        shopName: "§a§lHéro"
        shopPermission: "celeskyshop.Hero"
        shopLevel1: "celeskyshop.Hero.level1"
        shopLevel2: "celeskyshop.Hero.level2"
        shopLevel3: "celeskyshop.Hero.level3"
        shopLevel4: "celeskyshop.Hero.level4"
        shopLevel5: "celeskyshop.Hero.level5"
    Alchemist:
        UUID: "a43f6bb5-029c-2d2b-9613-849395feb969"
        shopName: "§a§lAlchimiste"
        shopPermission: "celeskyshop.Alchemist"
        shopLevel1: "celeskyshop.Alchemist.level1"
        shopLevel2: "celeskyshop.Alchemist.level2"
        shopLevel3: "celeskyshop.Alchemist.level3"
        shopLevel4: "celeskyshop.Alchemist.level4"
        shopLevel5: "celeskyshop.Alchemist.level5"