# You can scan UUID of entity with nether star
admin:
    checkUUID: "celeskyshop.admin.uuid"

# Sign buy system
signs:
    settings:
        world: "world"
        signTitle: "[AchatShop]"
    # You need to create on LuckPerm plugins 5 groups
    # Your groups if shop:<group>
    # Example : shop:ramasseur
    ranks:
        level1: "Ramasseur"
        level2: "Revendeur"
        level3: "Grossiste"
        level4: "Courtier"
        level5: "Magnat"

# NPC settings
sellers:
    Blocks: 
        enable: true
        UUID: ""
        shopName: "§a§lVendeur de blocs"
        shopPermission: "celeskyshop.Blocks"
        shopLevel1: "celeskyshop.Blocks.level1"
        shopLevel2: "celeskyshop.Blocks.level2"
        shopLevel3: "celeskyshop.Blocks.level3"
        shopLevel4: "celeskyshop.Blocks.level4"
        shopLevel5: "celeskyshop.Blocks.level5"
    Blacksmith: 
        enable: true
        UUID: ""
        shopName: "§a§lForgeron"
        shopPermission: "celeskyshop.Blacksmith"
        shopLevel1: "celeskyshop.Blacksmith.level1"
        shopLevel2: "celeskyshop.Blacksmith.level2"
        shopLevel3: "celeskyshop.Blacksmith.level3"
        shopLevel4: "celeskyshop.Blacksmith.level4"
        shopLevel5: "celeskyshop.Blacksmith.level5"
    Carpenter: 
        enable: true
        UUID: ""
        shopName: "§a§lMenuisier"
        shopPermission: "celeskyshop.Carpenter"
        shopLevel1: "celeskyshop.Carpenter.level1"
        shopLevel2: "celeskyshop.Carpenter.level2"
        shopLevel3: "celeskyshop.Carpenter.level3"
        shopLevel4: "celeskyshop.Carpenter.level4"
        shopLevel5: "celeskyshop.Carpenter.level5"
    Farmer: 
        enable: true
        UUID: ""
        shopName: "§a§lAgriculteur"
        shopPermission: "celeskyshop.Farmer"
        shopLevel1: "celeskyshop.Farmer.level1"
        shopLevel2: "celeskyshop.Farmer.level2"
        shopLevel3: "celeskyshop.Farmer.level3"
        shopLevel4: "celeskyshop.Farmer.level4"
        shopLevel5: "celeskyshop.Farmer.level5"
    Butcher: 
        enable: true
        UUID: ""
        shopName: "§a§lBoucher"
        shopPermission: "celeskyshop.Butcher"
        shopLevel1: "celeskyshop.Butcher.level1"
        shopLevel2: "celeskyshop.Butcher.level2"
        shopLevel3: "celeskyshop.Butcher.level3"
        shopLevel4: "celeskyshop.Butcher.level4"
        shopLevel5: "celeskyshop.Butcher.level5"
    Miner:
        enable: true
        UUID: ""
        shopName: "§a§lMineur"
        shopPermission: "celeskyshop.Miner"
        shopLevel1: "celeskyshop.Miner.level1"
        shopLevel2: "celeskyshop.Miner.level2"
        shopLevel3: "celeskyshop.Miner.level3"
        shopLevel4: "celeskyshop.Miner.level4"
        shopLevel5: "celeskyshop.Miner.level5"
    Magician:
        enable: true
        UUID: ""
        shopName: "§a§lMagicien"
        shopPermission: "celeskyshop.Magician"
        shopLevel1: "celeskyshop.Magician.level1"
        shopLevel2: "celeskyshop.Magician.level2"
        shopLevel3: "celeskyshop.Magician.level3"
        shopLevel4: "celeskyshop.Magician.level4"
        shopLevel5: "celeskyshop.Magician.level5"
    Engineer:
        enable: true
        UUID: ""
        shopName: "§a§lIngénieur"
        shopPermission: "celeskyshop.Engineer"
        shopLevel1: "celeskyshop.Engineer.level1"
        shopLevel2: "celeskyshop.Engineer.level2"
        shopLevel3: "celeskyshop.Engineer.level3"
        shopLevel4: "celeskyshop.Engineer.level4"
        shopLevel5: "celeskyshop.Engineer.level5"
    Adventurer:
        enable: true
        UUID: ""
        shopName: "§a§lAventurier"
        shopPermission: "celeskyshop.Adventurer"
        shopLevel1: "celeskyshop.Adventurer.level1"
        shopLevel2: "celeskyshop.Adventurer.level2"
        shopLevel3: "celeskyshop.Adventurer.level3"
        shopLevel4: "celeskyshop.Adventurer.level4"
        shopLevel5: "celeskyshop.Adventurer.level5"
    Hero:
        enable: true
        UUID: ""
        shopName: "§a§lHéro"
        shopPermission: "celeskyshop.Hero"
        shopLevel1: "celeskyshop.Hero.level1"
        shopLevel2: "celeskyshop.Hero.level2"
        shopLevel3: "celeskyshop.Hero.level3"
        shopLevel4: "celeskyshop.Hero.level4"
        shopLevel5: "celeskyshop.Hero.level5"
    Alchemist:
        enable: true
        UUID: ""
        shopName: "§a§lAlchimiste"
        shopPermission: "celeskyshop.Alchemist"
        shopLevel1: "celeskyshop.Alchemist.level1"
        shopLevel2: "celeskyshop.Alchemist.level2"
        shopLevel3: "celeskyshop.Alchemist.level3"
        shopLevel4: "celeskyshop.Alchemist.level4"
        shopLevel5: "celeskyshop.Alchemist.level5"
    Summoner:
        enable: true
        UUID: ""
        shopName: "§a§lInvocateur"
        shopPermission: "celeskyshop.Summoner"
        shopLevel1: "celeskyshop.Summoner.level1"
        shopLevel2: "celeskyshop.Summoner.level2"
        shopLevel3: "celeskyshop.Summoner.level3"
        shopLevel4: "celeskyshop.Summoner.level4"
        shopLevel5: "celeskyshop.Summoner.level5"